### ISSUE TITLE
Problem create volume HDD and SSD on OVH

### ISSUE THREAD

**Issue by cbouissoncs** [CS-SI/SafeScale#1]
Hello

When I want to create an SSD volume on OVH, it has the "classic" type.
When I want to create an HDD volume on OVH, it has the "high-speed" type.
When I want to create an COLD volume on OVH, it has the "high-speed" type (in fact, it has the same type of HDD)
Is that normal ?

Thank you in advance

**Comment by saimeCS** [comment]
On OVH, there are only 2 types of volume 'classic' and 'high-speed' albeit SafeScale proposes 3 types.
But I agree the mapping should be SSD -> High-speed, HDD & COLD -> classic.
This is due to an inconsistency between the definition of enums in protobuff and GO (inversed order).

**Comment by saimeCS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE#1](https://trello.com/c/oi3Y3i3F/1-issue1)

**Comment by saimeCS** [comment]
Fixed in #99d24814a50cdefd1a35a47bb644daf55b021c20
