### ISSUE TITLE
Building documentation obsolete

### ISSUE THREAD

**Issue by gbonnefille** [CS-SI/SafeScale#100]
The docs/BUILDING.md contains obsolete information:
* the directories of the binaries are incorrect (`lib/cli` instead of `cli`)
* the reference to scanner binary no more existing (possibly removed in 5f4c5e83c4b541f61d9392b638ac00cc04478ecc)

**Comment by vplanche-cssi** [comment]
Fixed and pushed in develop, commit 700b73f4e7f6178fa38db6eb5fdf588041364b31
