### ISSUE TITLE
Possible to disable docker install

### ISSUE THREAD

**Issue by cbouisson-csgroup** [CS-SI/SafeScale#105]
I would like to disable the installation of docker

**Comment by vplanche-cssi** [comment]
Currently, is not possible.

Docker is a "first-class" component that is needed for a lot of things in SafeScale.

What is the use-case ?

**Comment by oscarpicas** [comment]
Branch https://github.com/CS-SI/SafeScale/tree/feature/disable-docker fixes this issue.
Creating a cluster with "--disable docker" results in a cluster without docker nor remote desktop nor reverse proxy.

**Comment by oscarpicas** [comment]
Merged with develop
