### ISSUE TITLE
Only two masters created on a normal cluster

### ISSUE THREAD

**Issue by wruffine-csgroup** [CS-SI/SafeScale#113]
On Flexible Engine, when a cluster is created with the "normal" complexity, it only has two masters instead of the expected three (https://github.com/CS-SI/SafeScale/blob/release/v21.11/doc/USAGE.md#cluster).

**Comment by oscarpicas** [comment]
It seems the docs are not updated

**Comment by oscarpicas** [comment]
Fixed by https://github.com/CS-SI/SafeScale/commit/2f3e5cc48a97ed38337c96e0b5460089e91c60af

**Comment by cbouisson-csgroup** [comment]
Hello
It's not an update of doc that we need but really the creation of 3 masters for a NORMAL BOH cluster
Regards

**Comment by cbouisson-csgroup** [comment]
Finally e use LARGE configuration for BOH
I close issue
Regards
