### ISSUE TITLE
Broker resource extension mechanism

### ISSUE THREAD

**Issue by sdorgancs** [CS-SI/SafeScale#30]
Driver do not return all useful hardware info
- GPU Frequency
- Number of GPU
- GPU Type
Add an extension mechanism based on configuration file to complete info returned by driver
Driver should return default values for unknown info
Add supplementary info to command line
Ex: broker create test --gpu 2 --cpu-freq 2.8
This command shoud create a host with at least 2 GPU and a CPU core with a frequency higher than 3.2 GHz

**Comment by vplanche-cssi** [comment]
SafeScale provides a scanner that can complement information returned by Cloud Provider API to allow more precise selection of templates.
