### ISSUE TITLE
[doc] Host sizing 'template' component not documented

### ISSUE THREAD

**Issue by edepremare-cs** [CS-SI/SafeScale#307]
SafeScale allows via its cli to specify a 'template' in the sizing a of host to create, but this option is not referenced in the documentation, see [here](https://github.com/CS-SI/SafeScale/blob/develop/doc/USAGE.md)

It can still be found in by using the `safescale host create --help` command.

**Comment by oscarpicas** [comment]
Documented now in branch develop:
![image](https://user-images.githubusercontent.com/3659975/174319568-f25651ac-c46a-4512-9b08-d43850f41c51.png)

After PR: https://github.com/CS-SI/SafeScale/pull/315
