### ISSUE TITLE
Broker shell completion

### ISSUE THREAD

**Issue by sdorgancs** [CS-SI/SafeScale#34]
Create shell completion for bash and ssh

**Comment by sdorgancs** [comment]
Sorry ... Create completion for bash and zsh

**Comment by oscarpicas** [comment]
Implemented in commit: ae1da5d2f460ee23f038677955fc2a453c9c0255

**Comment by oscarpicas** [comment]
In SafeScale directory:

***Bash howto:***
sudo cp broker/cli/broker/autocomplete/bash/broker /etc/bash_completion.d/broker 

***Zsh howto:***
source broker/cli/broker/autocomplete/zsh/broker
