### ISSUE TITLE
Deploy completion shell

### ISSUE THREAD

**Issue by sdorgancs** [CS-SI/SafeScale#35]
Create completion for bash and zsh

**Comment by oscarpicas** [comment]
Implemented in : 4b1e8c289f052f4e8fc62f2243543e40d85c8ff1

**Comment by oscarpicas** [comment]
In SafeScale directory:

Bash howto:
sudo cp deploy/cli/autocomplete/bash/deploy /etc/bash_completion.d/deploy

Zsh howto:
source deploy/cli/autocomplete/zsh/deploy
