### ISSUE TITLE
Provide a compiled version for Windows, Linux and Mac

### ISSUE THREAD

**Issue by geonux** [CS-SI/SafeScale#40]
Provide a compiled version for Windows, Linux and Mac, with embedded SSH client.

**Comment by vplanche-cssi** [comment]
Linux amd64, macOS arm64 are fully supported and appropriate binaries are provided. macOS amd64 is fully supported, but appropriate binaries availability is more random (depending of the availability of the required hardware).

Windows is not supported, and there is no plan to do so at short term. Work is needed to make it work in native Windows, and more important features have to be introduced before Windows support.

Maybe the Linux amd64 binaries would work with the WSL? Not tested...
