### ISSUE TITLE
Cluster resume mode

### ISSUE THREAD

**Issue by geonux** [CS-SI/SafeScale#42]
Add the resume capability to continue the deployment after a failure.

**Comment by vplanche-cssi** [comment]
deploy is not a part of SafeScale anymore.

Ability to resume a cluster creation is in study.

**Comment by oscarpicas** [comment]
Current behavior is: when a cluster is being created and a machine fails for any reason, a new machine takes its place until the expected number of gateways/nodes/masters is reached
