### ISSUE TITLE
Ability to specify a template manually

### ISSUE THREAD

**Issue by svergnaudcs** [CS-SI/SafeScale#43]
On FlexibleEngine , when creating a VM with 4 vCPUs and 32GB MEMORY, brokerd has the choice between the 2 following templates:
- d2.xlarge.8 (4 vCPU, 32GB RAM, 2*1.8TB) : 439,07 € / month
- m1.xlarge (4 vCPU, 32GB RAM) : 161,53 € / month

The problem is that the prices are not returned by FE's API so that the brokerd algorithm chooses the template by alphabetical order : here the most expensive

Question : how to manually specify the template's name to use ?
Thanks in advance
Rgds.

**Comment by sdorgancs** [comment]
This is a bug, SafeScale should choose the VM with the smallest disk: m1.xlarge
