### ISSUE TITLE
Issues provisioning network to T systems cloud

### ISSUE THREAD

**Issue by PYMartres** [CS-SI/SafeScale#44]
Hello,

I have trouble provisioning network to T-Systems cloud using the following command:
/broker network create networktest --cpu 2 --ram 2 --disk 20000

The error returned by the broker is:
2018/11/26 09:16:01 Create Network called
2018/11/26 09:17:08 ProviderErrorToString(*errors.errorString)
2018/11/26 09:17:08 ProviderErrorToString(*errors.errorString)
2018/11/26 09:17:10 flexibleengine.Client.deleteSubnet(fa169468-65ae-4dc4-a2a6-c1c19b3cb22e): try #1, verdict=Done, err: '<nil>'
2018/11/26 09:17:11 error creating gateway : timeout waiting host 'gw-networktest' ready: host 'gw-networktest' is in 'ERROR' state

Can you please help me?
Thanks.

**Comment by vplanche-cssi** [comment]
Hello,

I see 2 points :

1. when a host status becomes ERROR during the timeout, the provider failed to create a viable host. Nothing can be done in this case except destroy the host manually from the provider console then retry.

2. You asked a system disk of 20000 GB = 20 TB of system disk (the unit is GB). It is probably beyond the quota you have, and may be the reason the host status became ERROR.

Regards.

**Comment by PYMartres** [comment]
Thank you for answering this fast.

I thought the unit was MB because of the default comportment was provisioning 100MB.
I retried provisioning 20 GB and I just get the same error, I tried multiple times unsuccessfully.

**Comment by vplanche-cssi** [comment]
You should go to the console of the provider, to see if there are some logs explaining the reason of the ERROR state for the host. Without more details, it's impossible to tell what's going on.
