### ISSUE TITLE
Broker inspect does not show disk size

### ISSUE THREAD

**Issue by svergnaudcs** [CS-SI/SafeScale#50]
When running a **broker inspect**, the host disk size is not returned:
`{
  "ID": "",
  "Name": "",
  "CPU": ,
  "RAM": ,
  "PublicIP": "",
  "PrivateIP": "",
  "State": ,
  "PrivateKey": ""
}`
As the disk size allocated by the cloud provider can be different from the disk size required when creating the host, we need this information
Thanks for your help

**Comment by oscarpicas** [comment]
Which version are you using ?

Here is the output of broker (develop branch, version 0.1.1)

broker host inspect gw-sample | prettyjson
{
    "CPU": 1,
    **"Disk": 20,**
    "ID": "0d09150c-b2c5-4f82-a5e2-97103fd88269",
    "Name": "gw-sample",
    "PrivateIP": "192.168.0.1",
    "PrivateKey": "-----BEGIN RSA PRIVATE KEY-----\nMI

**Comment by svergnaudcs** [comment]
Oscar,
I'm also using version 0.1.1: Brokerd version: 0.1.1, build date: 2018-11-28 16:34
The host I'm trying to inpect was created via command "broker network create", it's named "gw-rus-net"

Rgds

**Comment by oscarpicas** [comment]
Which provider / tenant are you using ?

Is it a reproducible error ?
Do you see errors on brokerd logs ? (look at file ~/.safescale/brokerd-session.log)

**Comment by oscarpicas** [comment]
Can you send us the output of `git rev-parse HEAD` ?

**Comment by svergnaudcs** [comment]
Oscar,
To answer your questions:
_Is it a reproducible error ?
Can you send us the output of git rev-parse HEAD ?_
=> I didn't clone the repository but downloaded brokerd & broker binaries directly from github (https://github.com/CS-SI/SafeScale/releases/download/v0.1.1/broker & https://github.com/CS-SI/SafeScale/releases/download/v0.1.1/brokerd) so that I can't send you the output of "git rev-parse HEAD"
To reproduce, simply download these two binaries and execute a docker inspect.

_Do you see errors on brokerd logs ? (look at file ~/.safescale/brokerd-session.log)_
=> No I don't see any error

Rgds.

**Comment by vplanche-cssi** [comment]
Size of disk isn't save correctly for FlexibleEngine/OpenTelekom. The disk size being zero in template, the corresponding field isn't displayed at all (proto defines json tag on it with option omitempty).

**Comment by vplanche-cssi** [comment]
Fixed in commit 07a128c60f89c715d3b3c50ebcf79d241881b170
