### ISSUE TITLE
Error "Failed to create host '%HOSTNAME%': name is already used"

### ISSUE THREAD

**Issue by svergnaudcs** [CS-SI/SafeScale#52]
When trying to create the host "front-usr-test", I receive the following message:
`Failed to create host 'front-usr-test': name is already used`
The VM does not exist on the tenant nor in the object storage.

For information, a machine named "front-usr-test-firefox" already exists on the tenant (but not in the object storage as it was created by RUS)
Could this be linked ?

Rgds.

**Comment by vplanche-cssi** [comment]
GetHostByName(): the openstack search isn't an exact match, but a pattern match. Every host which name begins with the search string is selected.

**Comment by vplanche-cssi** [comment]
Fixed in commit 0be39324748fd4e833dab7b8268c7ff7011e7e6c
