### ISSUE TITLE
Build does not work with go 1.11

### ISSUE THREAD

**Issue by sdorgancs** [CS-SI/SafeScale#55]
stringer needs to be updated to work with go 1.11
@(dep ensure -update "golang.org/x/tools")

**Comment by oscarpicas** [comment]
Not really: in a build from scratch, dep already retrieves last stringer version.
However, if you updated go from 1.10 to 1.11 you might find this issue.

I'll modify the Makefile to take into account this upgrade.

**Comment by oscarpicas** [comment]
Fixed a vet error building the master in commit c5c3c355a6cbc4680455fb120c0afdb8fb3ccdc9
Issue #55
