### ISSUE TITLE
Ability to update metadata

### ISSUE THREAD

**Issue by svergnaudcs** [CS-SI/SafeScale#57]
Dear All,
On the RUS project, we are often asked to extend VM physical caracteristics.
For example, if the basic user needs are underestimated, we can be asked to add more CPU, RAM or disk space.
These operations were initially executed by the RUS code
Now with safescale, if we manually modify one of these caracteristics, how to update safescale metadata so that the changes are taken into account ?

Thanks in advance.
Rgds

**Comment by vplanche-cssi** [comment]
For obvious reasons, we won't provide to user the ability to modify directly the metadata. This will barely lead to systematic disaster.
The good response is to implement resize abilities in SafeScale.
