### ISSUE TITLE
Implements CPU/RAM/system disk resize in safescale

### ISSUE THREAD

**Issue by vplanche-cssi** [CS-SI/SafeScale#58]
Following issue #57.

SafeScale broker should be able to increase (at minimum) CPU, RAM and System Disk size.

If possible (maybe provider dependent), implement also decrease.

**Comment by oscarpicas** [comment]
Skeleton implemented in 8a3247e3b8ba26711dfa21ec6f589035e3390079

We need to discuss volume resizing options first.

**Comment by vplanche-cssi** [comment]
Added in backlog, but not planned for now. Relabelled as `feature request`.
