### ISSUE TITLE
Delete metadata for failed deployments

### ISSUE THREAD

**Issue by PYMartres** [CS-SI/SafeScale#59]
Hi,

Could you please tell me how to delete metadata for failed deployments.
For example when I use the command broker host list, I see hosts that no longer exist and I  can't delete it with the regular broker host delete command.

Thank you.

**Comment by oscarpicas** [comment]
Until we add a purge command to clean up obsolete metadata, the only way is to delete metadata manually...

Take a look at 
`SafeScale/doc/METADATA.md`

**Comment by PYMartres** [comment]
Found everything I needed, thank you for support.
