### ISSUE TITLE
[BROKER] Volumes attached to an host are not displayed on "./broker host inspect"

### ISSUE THREAD

**Issue by svergnaudcs** [CS-SI/SafeScale#60]
Dear all,
When attaching a volume to an host, a `./broker inspect volume <volume_id>` shows the host on which it is attached but a `./broker inspect host <host_id>` does not show the volumes attached to the host.

Thanks for the help
Rgds.

**Comment by oscarpicas** [comment]
Sample output of a `./broker host inspect ...`
```

{
    "AttachedVolumeNames": [
        "fuchsia"
    ],
    "CPU": 1,
    "Disk": 20,
    "ID": "41811433-99fa-465a-bad4-7eb2851406e1",

```
