### ISSUE TITLE
Issue provisoning network to Orange cloud

### ISSUE THREAD

**Issue by PYMartres** [CS-SI/SafeScale#63]
Hello,

I try provisioning a network to orange business cloud and I have the following error message.
I previously deleted my safescale bucket to delete metadata on orange cloud.

./broker network create --cidr "192.168.3.0/24" test
Put, uploading object: NoSuchBucket: The specified bucket does not exist status code: 404, request id: 006700000167C60CCD20087D06073B47, host id: GBZ/W63181aoU1f0SXAHtxFvyc8rSuKtpkPWBxP/GnlZ4bpv7uzC3FTFHYNyjFPn

Thank you for support.

**Comment by PYMartres** [comment]
The server stacktrace:

Ready to serve :-)
ERROR   [2018-12-19 10:39:47] NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: 006700000167C60CCD20087D06073B47, host id: GBZ/W63181aoU1f0SXAHtxFvyc8rSuKtpkPWBxP/GnlZ4bpv7uzC3FTFHYNyjFPn
Put, uploading object
github.com/CS-SI/SafeScale/vendor/github.com/graymeta/stow/s3.(*container).Put
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/github.com/graymeta/stow/s3/container.go:137
github.com/CS-SI/SafeScale/providers/objectstorage.(*object).Write
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/objectstorage/object.go:175
github.com/CS-SI/SafeScale/providers/objectstorage.(*bucket).WriteObject
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/objectstorage/bucket.go:172
github.com/CS-SI/SafeScale/utils/metadata.(*Folder).Write
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/utils/metadata/folder.go:170
github.com/CS-SI/SafeScale/utils/metadata.(*Item).WriteInto
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/utils/metadata/item.go:137
github.com/CS-SI/SafeScale/providers/metadata.(*Network).Write
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/metadata/network.go:92
github.com/CS-SI/SafeScale/providers/metadata.SaveNetwork
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/metadata/network.go:301
github.com/CS-SI/SafeScale/broker/server/services.(*NetworkService).Create
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/services/network.go:116
github.com/CS-SI/SafeScale/broker/server/listeners.(*NetworkServiceListener).Create
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/listeners/network.go:51
github.com/CS-SI/SafeScale/broker._NetworkService_Create_Handler
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/broker.pb.go:2459
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:982
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).handleStream
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:1208
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:686
runtime.goexit
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361

**Comment by vplanche-cssi** [comment]
Bucket is create when tenant is set. If you delete the bucket after ```broker tenant set <your tenant>```, this behaviour is normal (but not necessarily sufficiently handled for now).

I suggest you stop brokerd and restart it, then do a ```broker tenant set <your tenant>```

to see if the bucket is created as expected (you could also change tenant and come back to the original, it has the same effect, but you need to have at least 2 working tenants).

**Comment by vplanche-cssi** [comment]
Could you share with us your tenants.toml file (with authentication related information scrambled) ?

**Comment by PYMartres** [comment]
If you want so but i think there's a misunderstanding on my side, in fact, the question is is it possible to work on two regions for the same tenant (in my tenants.toml file, all information about orange_eu and orange_asia tenant are just the same except the region to work on).

**Comment by vplanche-cssi** [comment]
Yes it's possible. The Object Storage of the region is used. It may be something wrong in your ```tenants.toml``` file.

**Comment by vplanche-cssi** [comment]
Your ```tenants.toml``` file is fine to me...

After a second thought, I think this is related to some unexpected behaviour at the provider side. From the provider documentation, error code 301 means "PermanentRedirect: The requested bucket must be addressed using a specified endpoint. Send all future requests to the endpoint.". So according to this message, I understand the endpoint used is not the good one, maybe there is no Object Storage facility in Asia.

I'll contact Orange to have more information about this case and keep you informed.

**Comment by PYMartres** [comment]
Thank you.

**Comment by vplanche-cssi** [comment]
This issue is solved in develop branch, and in the coming really soon 19.03.0 release.
