### ISSUE TITLE
SIGSEGV: segmentation violation when creating an host

### ISSUE THREAD

**Issue by PYMartres** [CS-SI/SafeScale#64]
Hello, my safescale broker displays the following error when I try creating an host on T-Systems cloud with the command:

broker host create --cpu 4 --ram 2 --disk 30 --os "Ubuntu 16.04" --net Int_Network6 Instance14

I already created two other hosts with almost the same command (only the name changed, same network), the host is diplayed in the t-systems console as "faulty".

Error from the broker below:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xf80481]

goroutine 2848 [running]:
github.com/CS-SI/SafeScale/broker/server/handlers.(*HostHandler).Create(0xc42000e020, 0xc420366050, 0xf, 0xc420a4a080, 0x11, 0x4, 0x40000000, 0x1e, 0xc420366060, 0xc, ...)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/handlers/host.go:329 +0x1421
github.com/CS-SI/SafeScale/broker/server/listeners.(*HostListener).Create(0x18d28f0, 0x1334c80, 0xc4204c0420, 0xc4201841c0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/listeners/host.go:173 +0x4ad
github.com/CS-SI/SafeScale/broker._HostService_Create_Handler(0x116bf40, 0x18d28f0, 0x1334c80, 0xc4204c0420, 0xc4201840e0, 0x0, 0x0, 0x0, 0xc420f0472f, 0xc420394000)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/broker.pb.go:2696 +0x306
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420001380, 0x133a120, 0xc4219b4480, 0xc420466100, 0xc4203deff0, 0x18a78c0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:982 +0xb1c
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420001380, 0x133a120, 0xc4219b4480, 0xc420466100, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:1208 +0x137d
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202c00c0, 0xc420001380, 0x133a120, 0xc4219b4480, 0xc420466100)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:686 +0xad
created by github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:684 +0xb9

**Comment by oscarpicas** [comment]
Commit 185a5df151a393a06dfff373d69b5b814e7602ce should fix the SIGSEGV

**Comment by PYMartres** [comment]
Hello,

Just tested, everything seems to be ok.

Thank you for support.
