### ISSUE TITLE
Issues provisioning private images

### ISSUE THREAD

**Issue by PYMartres** [CS-SI/SafeScale#66]
Hello,

When I try provisioning private images with Safescale, I have the following error as the demon crashes:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf563b8]

goroutine 604 [running]:
github.com/CS-SI/SafeScale/providers/flexibleengine.(*Client).CreateHost.func1(0x0, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/flexibleengine/compute.go:444 +0x688
github.com/CS-SI/SafeScale/utils/retry.action.loop(0xc4203e0310, 0xc420434700, 0x0, 0xc4204a8e20, 0x0, 0x0, 0x30, 0x28)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/utils/retry/action.go:303 +0xc4
github.com/CS-SI/SafeScale/utils/retry.WhileUnsuccessful(0xc4204c2e20, 0x12a05f200, 0x8bb2c97000, 0x30, 0x1160340)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/utils/retry/action.go:96 +0x107
github.com/CS-SI/SafeScale/utils/retry.WhileUnsuccessfulDelay5Seconds(0xc4204c2e20, 0x8bb2c97000, 0x1, 0x10293c0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/utils/retry/action.go:129 +0x52
github.com/CS-SI/SafeScale/providers/flexibleengine.(*Client).CreateHost(0xc4203da600, 0xc420407080, 0xe, 0x0, 0x0, 0xc42000e2f0, 0x1, 0x1, 0xc4203dba40, 0x0, ...)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/providers/flexibleengine/compute.go:432 +0x143f
github.com/CS-SI/SafeScale/broker/server/handlers.(*HostHandler).Create(0xc42000e1c0, 0xc420407080, 0xe, 0xc4202123e0, 0x11, 0x4, 0x40000000, 0x1e, 0xc420407090, 0x7, ...)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/handlers/host.go:308 +0x105a
github.com/CS-SI/SafeScale/broker/server/listeners.(*HostListener).Create(0x18d28f0, 0x1334c20, 0xc42026e6c0, 0xc4203e8bd0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/server/listeners/host.go:173 +0x4ad
github.com/CS-SI/SafeScale/broker._HostService_Create_Handler(0x116bf40, 0x18d28f0, 0x1334c20, 0xc42026e6c0, 0xc4203e8af0, 0x0, 0x0, 0x0, 0xc42056a094, 0xc420bc2d80)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/broker/broker.pb.go:2696 +0x306
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420090300, 0x133a0c0, 0xc420456f00, 0xc4200d0500, 0xc4203c6ff0, 0x18a78c0, 0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:982 +0xb1c
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420090300, 0x133a0c0, 0xc420456f00, 0xc4200d0500, 0x0)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:1208 +0x137d
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420407010, 0xc420090300, 0x133a0c0, 0xc420456f00, 0xc4200d0500)
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:686 +0xad
created by github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:684 +0xb9

The build I use is the following 
https://github.com/CS-SI/SafeScale/commit/185a5df151a393a06dfff373d69b5b814e7602ce

**Comment by oscarpicas** [comment]
Download and apply the patch found in 

https://github.com/CS-SI/SafeScale/blob/develop/support/patches/Fix_issue_66.patch

with `git apply`
