### ISSUE TITLE
Impossible to create a public host on flexible-engine

### ISSUE THREAD

**Issue by AJouaneau-CS** [CS-SI/SafeScale#71]
$ ssc host create --public publichost
{"status":"failure","error":{"message":"Can't create subnet with CIDR '10.0.0.0/8': not inside VPC CIDR '192.168.0.0/16'","exitcode":6},"result":null}
It's not possible to set the CIDR and the default one is not part of the VPC CIDR
Currently the only workaround is to use the gateway of a network where it's possible to edit the cidr

**Comment by vplanche-cssi** [comment]
Fixed.
