### ISSUE TITLE
Problems using BOH cluster

### ISSUE THREAD

**Issue by SebastienDorgan** [CS-SI/SafeScale#73]
Creation of a BOH complexity simple under centos 7
$ sc cluster create -F BOH --os centos7 --sizing="cpu=16,ram=60" s2.pdgs.com
- Guacamole does not work
- hosts files are not set
- ssh keys are not installed
- error when I try to expand the cluster:
$ sc cluster expand --count 2 s2.pdgs.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1022076]

goroutine 1 [running]:
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*Controller).AddNodes.func2(0x16bfbe0, 0xc00065e5a0, 0xc00065e5a0, 0x1acc340)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/controller.go:499 +0x246
github.com/CS-SI/SafeScale/lib/utils/serialize.(*SyncedJSONProperty).ThenUse(0xc0005da7b0, 0xc0005a7fc0, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/utils/serialize/json.go:68 +0x152
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*Controller).AddNodes(0xc00030bcb0, 0x1ad4f00, 0xc0002b8240, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/controller.go:496 +0x309
github.com/CS-SI/SafeScale/cli/safescale/commands.glob..func20(0xc0000dc6e0, 0xc0000dc6e0, 0x1869c9c)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/cli/safescale/commands/cluster.go:746 +0x1ae
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.HandleAction(0x15fe9e0, 0x1908ab8, 0xc0000dc6e0, 0xc000031500, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:490 +0xfe
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x186ba7d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x187948c, 0x12, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:210 +0xcdf
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000e4b60, 0xc0000dc420, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:379 +0xd44
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.startApp(0x186cf5d, 0x7, 0x0, 0x0, 0x258dc60, 0x3, 0x3, 0x188118c, 0x19, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:298 +0x119a
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x186cf5d, 0x7, 0x0, 0x0, 0x258dc60, 0x3, 0x3, 0x188118c, 0x19, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:98 +0x17c3
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).Run(0xc0000e4820, 0xc0000c8120, 0x6, 0x6, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:255 +0xa64
main.main()
        /home/vincent/go/src/github.com/CS-SI/SafeScale/cli/safescale/main.go:160 +0x1756
same thing with:
$ sc cluster expand --count 2 --node-sizing="cpu=16,ram=60" s2.pdgs.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1022076]

goroutine 1 [running]:
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*Controller).AddNodes.func2(0x16bfbe0, 0xc0006fe780, 0xc0006fe780, 0x1acc340)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/controller.go:499 +0x246
github.com/CS-SI/SafeScale/lib/utils/serialize.(*SyncedJSONProperty).ThenUse(0xc00060a0a0, 0xc000749fc0, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/utils/serialize/json.go:68 +0x152
github.com/CS-SI/SafeScale/lib/server/cluster/control.(*Controller).AddNodes(0xc0006801b0, 0x1ad4f00, 0xc0005a6240, 0x2, 0xc000722000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/lib/server/cluster/control/controller.go:496 +0x309
github.com/CS-SI/SafeScale/cli/safescale/commands.glob..func20(0xc0000e06e0, 0xc0000e06e0, 0x1869c9c)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/cli/safescale/commands/cluster.go:746 +0x1ae
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.HandleAction(0x15fe9e0, 0x1908ab8, 0xc0000e06e0, 0xc0005af200, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:490 +0xfe
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x186ba7d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x187948c, 0x12, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:210 +0xcdf
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000e8b60, 0xc0000e0420, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:379 +0xd44
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.startApp(0x186cf5d, 0x7, 0x0, 0x0, 0x258dc60, 0x3, 0x3, 0x188118c, 0x19, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:298 +0x119a
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.Command.Run(0x186cf5d, 0x7, 0x0, 0x0, 0x258dc60, 0x3, 0x3, 0x188118c, 0x19, 0x0, ...)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/command.go:98 +0x17c3
github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli.(*App).Run(0xc0000e8820, 0xc0000ce000, 0x7, 0x7, 0x0, 0x0)
        /home/vincent/go/src/github.com/CS-SI/SafeScale/vendor/github.com/urfave/cli/app.go:255 +0xa64
main.main()
        /home/vincent/go/src/github.com/CS-SI/SafeScale/cli/safescale/main.go:160 +0x1756

**Comment by oscarpicas** [comment]
Hi
Which version are you running ? Is the last revision of the "develop" branch ? If not, which is the "commit id" ?

**Comment by SebastienDorgan** [comment]
I am running the last release SafeScale v19.06.1

**Comment by oscarpicas** [comment]
There was a recent issue with centos7, try the same command with ubuntu

**Comment by SebastienDorgan** [comment]
unfortunately I have to use centos

**Comment by oscarpicas** [comment]
If we confirm your problem with the binaries from v19.06.1, we'll mark this as a bug, then release a bugfix v19.06.2 asap.

In the meantime, you can try the same command with the last version from the develop branch.

**Comment by oscarpicas** [comment]
Hi
We tested the same command:
$ sc cluster create -F BOH --os centos7 --sizing="cpu=16,ram=60" s2.pdgs.com
and worked flawlessly, in order to fix your problem we need to look at your safescaled logs.

But the problem expanding the cluster:
$ sc cluster expand --count 2 s2.pdgs.com
IS indeed a bug and needs to be fixed

**Comment by SebastienDorgan** [comment]
[safescaled-session.log](https://github.com/CS-SI/SafeScale/files/3516653/safescaled-session.log)
Good luck, I try this morning around 9

**Comment by vplanche-cssi** [comment]
Fixed in release v19.10.0
