### ISSUE TITLE
create host help command

### ISSUE THREAD

**Issue by SebastienDorgan** [CS-SI/SafeScale#74]
It is writen
"<cpufreq> is expecting an int as minimum cpu frequency in MHz"
But when I inspect the log I see:
"Unable to create a host with '-1' GPUs and a CPU clock frequencyof '3000.0 GHz', no images matching requirements"
The log is also wrong it should be:
"Unable to create a host with '-1' GPUs and a CPU clock frequency of '3000.0 GHz', no template matching requirements"

**Comment by vplanche-cssi** [comment]
Fixed in v19.09.1.
