### ISSUE TITLE
Create host sizing

### ISSUE THREAD

**Issue by SebastienDorgan** [CS-SI/SafeScale#75]
I run the scanner on my tenant and the cpu frequency is not extracted from the hosts anymore:
{
      "cores": 2,
      "ram_size": 15,
      "disk_size": 50,
      "id": "654b2e23-39f5-4dd2-bd0f-feb6a638dc2c",
      "name": "r2-15"
    },
As a result it is not possible to use the cpufreq property to select a template when creating an host

**Comment by oscarpicas** [comment]
Hi

This is a output fragment of a recent scanner execution:
{
        ....
        "number_of_socket": 8,
	**"cpu_frequency_Ghz"**: 2.99296,
	"cpu_arch": "x86_64",
	"hypervisor": "KVM",
	"cpu_model": "Intel Core Processor (Haswell, no TSX)",
	**"ram_size_Gb"**: 28.75,
	**"disk_size_Gb"**: 200,
        ...
}

notice that last version (develop branch), includes size information with units, this means that you are not using that version.

Please test again with the last version from develop branch and let us know if the problem extracting cpu frequency persists.

**Comment by SebastienDorgan** [comment]
ok, I let you know.
When do you plan to create a new release, 19.06.1 is really not stable?

**Comment by oscarpicas** [comment]
It should be stable.
However, if those issues are confirmed it means that we must take a second look at our integration tests to ensure it doesn’t happen again, then release the bugfix

**Comment by SebastienDorgan** [comment]
With the develop branch the scanner fails on each template with the following error:
DEBUG   [25434][2019-08-19 16:14:33] Remote SSH NOT ready: error code: 1; Output []; Error [cat: /opt/safescale/var/state/user_data.phase2.done: No such file or directory

**Comment by SebastienDorgan** [comment]
Yes the last version of the develop branch

**Comment by oscarpicas** [comment]
This bug was fixed yesterday, you should update again
