### ISSUE TITLE
Create host

### ISSUE THREAD

**Issue by SebastienDorgan** [CS-SI/SafeScale#76]
With SafeScale version Safescaled version: 19.09.0-alpha (built from develop branch) 
When I run on ovh: 
>> sc host create --public -os "Centos 7" --sizing="cpu=16, ram=30, disk=100" master.s2.pdgs.com
{"status":"failure","error":{"message":"Failed to find template corresponding to requested resources:","exitcode":6},"result":null}
With the log:
ERROR   [ 9966][2019-08-29 07:50:45] failed to find template corresponding to requested resources 
ERROR   [ 9966][2019-08-29 07:50:45] 
failed to find template corresponding to requested resources
github.com/CS-SI/SafeScale/lib/server/handlers.logicErrf
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/lib/server/handlers/logsetup.go:133
github.com/CS-SI/SafeScale/lib/server/handlers.(*HostHandler).Create
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/lib/server/handlers/host.go:316
github.com/CS-SI/SafeScale/lib/server/listeners.(*HostListener).Create
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/lib/server/listeners/host.go:219
github.com/CS-SI/SafeScale/lib._HostService_Create_Handler
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/lib/safescale.pb.go:3542
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:982
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).handleStream
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:1208
github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
        /home/sdorgan/Desktop/Projects/go/src/github.com/CS-SI/SafeScale/vendor/google.golang.org/grpc/server.go:686
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by vplanche-cssi** [comment]
What provider was used ?

**Comment by SebastienDorgan** [comment]
OVH

**Comment by vplanche-cssi** [comment]
There has been a behavioural change with --sizing : when `=` is used, it means `exact match`.
It appears that there is no template with 16 cores, 30 GB of RAM and 100 GB of disk proposed by OVH.
The closer template has 16 cores, 60 GB of RAM and 100 GB of disk.
To be able to select this one, you should use --sizing "cpu>=16,ram>=30,disk >=100", or --sizing=[16-20],ram=[30-64],disk>=100" to impose lower and upper limits.

I agree that the documentation is not up-to-date on this point and need to be fixed. I'll keep this issue opened for this purpose (and for more if my solution doesn't solve your issue, of course).

**Comment by vplanche-cssi** [comment]
Fixed in release v19.10.1.
