### ISSUE TITLE
SizingRequirements wording

### ISSUE THREAD

**Issue by sdorgancs** [CS-SI/SafeScale#78]
the 'replaceable' term used to designate SPOT type instances seems not correct to me. A more consensual term would be 'preemptible'.

**Comment by vplanche-cssi** [comment]
This term points to special kind of host resource that may disappear without notice, to be marked as "replaceable" meaning if it disappears it has to be creating from scratch again.

But this is WIP, and nothing is frozen yet. There is one more important point to think about : does such a resource have to be recreated automatically or manually ? If automatically, how SafeScale detect its disapperance ?

**Comment by sdorgancs** [comment]
Ok I understand what you mean.
In my opinion independently of the provider wording/marketing, preemptible is better because recreating might be another feature applicable also to non preemptible instances (in case of crash).

**Comment by vplanche-cssi** [comment]
Premptible terminology adopted.
