### ISSUE TITLE
If cluster expand fails, subsequent calls of cluster expand fail on host not found error

### ISSUE THREAD

**Issue by vplanche-cssi** [CS-SI/SafeScale#80]
Logs from first try:

bash -c ssh -i /tmp/176959847 -q -oIdentitiesOnly=yes
-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null
-oPubkeyAuthentication=yes -oPasswordAuthentication=no
-oLogLevel=error -p 34473 safescale@127.0.0.1 <<'ENDSSH'
                              [4/233]sudo bash
/opt/safescale/var/tmp/feature.docker.add_docker-compose.sh; rc=$?;
exit $rc
ENDSSH
TRACE   [2020-03-31 07:20:30.192][trace][31089] <<<
system.(*SSHCommand).RunWithTimeout(COLLECT, 10m0s)
[lib/system/ssh.go:128] (duration: 00h03m01.952s)
TRACE   [2020-03-31 07:20:30.193][trace][31089] --- {task
0a4db432-15ca-423a-9c99-a867287876ed} install.(*step).Run()
[lib/server/install/step.go:174]: :
Add(docker):step(docker-compose)@ab-node-4 failed in 00h03m06.249s:
ab-node-4: failure: retcode=193
DEBUG   [2020-03-31 07:20:30.193][debug][31089] Ending step
'docker-compose' on 1 host (elapsed: 00h03m06.250s)
TRACE   [2020-03-31 07:20:30.193][trace][31089] <<< {task
0a4db432-15ca-423a-9c99-a867287876ed} install.(*step).Run()
[lib/server/install/step.go:128]
DEBUG   [2020-03-31 07:20:30.193][debug][31089] Ending execution of
step 'Add::docker-compose' (elapsed: 00h03m06.250s)
ERROR   [2020-03-31 07:20:30.193][error][31089] executed step
'Add::docker-compose' ERROR OCCURRED: ab-node-4: failure: retcode=193
INFO    [2020-03-31 07:20:30.193][info][31089] Ending addition of
feature 'docker' on host 'ab-node-4' (elapsed: 00h04m12.660s)
ERROR   [2020-03-31 07:20:30.193][error][31089] --- {task
0a4db432-15ca-423a-9c99-a867287876ed} install.(*Feature).Add():
'docker' on host 'ab-node-4' [lib/server/install/feature.go:174]:
ERROR OCCURRED: ab-node-4: failure: retcode=193
TRACE   [2020-03-31 07:20:30.193][trace][31089] <<< {task
0a4db432-15ca-423a-9c99-a867287876ed} install.(*Feature).Add():
'docker' on host 'ab-node-4' [lib/server/install/feature.go:128]
(duration: 00h04m12.660s)
ERROR   [2020-03-31 07:20:30.193][error][31089] --- {task
0a4db432-15ca-423a-9c99-a867287876ed}
control.(*foreman).installDocker()
[lib/server/cluster/control/foreman.go:174]:  ERROR OCCURRED:
ab-node-4: failure: retcode=193
TRACE   [2020-03-31 07:20:30.193][trace][31089] <<< {task
0a4db432-15ca-423a-9c99-a867287876ed}
control.(*foreman).installDocker()
[lib/server/cluster/control/foreman.go:128] (duration: 00h04m12.660s)
ERROR   [2020-03-31 07:20:30.193][error][31089] --- {task
0a4db432-15ca-423a-9c99-a867287876ed}
control.(*foreman).taskConfigureNode(1, ab-node-4)
[lib/server/cluster/control/foreman.go:174]:  ERROR OCCURRED:
ab-node-4: failure: retcode=193
TRACE   [2020-03-31 07:20:30.193][trace][31089] <<< {task
0a4db432-15ca-423a-9c99-a867287876ed}
control.(*foreman).taskConfigureNode(1, ab-node-4)
[lib/server/cluster/control/foreman.go:128] (duration: 00h04m12.661s)
ERROR   [2020-03-31 07:20:30.193][error][31089] --- {task
1ea8396a-68db-47bc-be94-5ee8858c8389}
control.(*foreman).configureNodesFromList()
[lib/server/cluster/control/foreman.go:174]:  ERROR OCCURRED:
ab-node-4: failure: retcode=193
TRACE   [2020-03-31 07:20:30.193][trace][31089] <<< {task
1ea8396a-68db-47bc-be94-5ee8858c8389}
control.(*foreman).configureNodesFromList()
[lib/server/cluster/control/foreman.go:128]
ERROR   [2020-03-31 07:20:44.657][error][31089] trying to add error
[%!s(<nil>)] to existing error [ab-node-4: failure: retcode=193]
but failed
ERROR   [2020-03-31 07:20:44.657][error][31089] --- {task
1ea8396a-68db-47bc-be94-5ee8858c8389}
control.(*Controller).AddNodes(1)
[lib/server/cluster/control/controller.go:174]:  ERROR OCCURRED:
ab-node-4: failure: retcode=193
TRACE   [2020-03-31 07:20:44.657][trace][31089] <<< {task
1ea8396a-68db-47bc-be94-5ee8858c8389}
control.(*Controller).AddNodes(1)
[lib/server/cluster/control/controller.go:128]
{"error":{"exitcode":6,"message":"ab-node-4: failure:
retcode=193\n"},"result":null,"status":"failure"}

Following try:
INFO    [2020-03-31 07:26:53.092][info][31694] Starting addition of
feature 'kubernetes' on cluster 'ab'...
TRACE   [2020-03-31 07:26:53.093][trace][31694] >>> {task
fb05f3f6-2095-48e8-b43c-725748e15bdf} install.(*Feature).Check():
'kubernetes' on cluster 'ab' [lib/server/install/feature.go:103]
DEBUG   [2020-03-31 07:26:53.093][debug][31694] Checking if feature
'kubernetes' is installed on cluster 'ab'...
DEBUG   [2020-03-31 07:26:53.094][debug][31694] Starting execution
of step 'Check::nodes'...
DEBUG   [2020-03-31 07:26:58.263][debug][31694] Ending execution of
step 'Check::nodes' (elapsed: 00h00m05.168s)
ERROR   [2020-03-31 07:26:58.263][error][31694] executed step
'Check::nodes' ERROR OCCURRED: rpc error: code = Internal desc =
cannot inspect host: failed to find host
'316e9d97-5823-4ebf-a6f8-9552d786056d'
ERROR   [2020-03-31 07:26:58.263][error][31694] --- {task
fb05f3f6-2095-48e8-b43c-725748e15bdf} install.(*Feature).Check():
'kubernetes' on cluster 'ab' [lib/server/install/feature.go:174]:
ERROR OCCURRED: rpc error: code = Internal desc = cannot inspect
host: failed to
find host '316e9d97-5823-4ebf-a6f8-9552d786056d'
TRACE   [2020-03-31 07:26:58.263][trace][31694] <<< {task
fb05f3f6-2095-48e8-b43c-725748e15bdf} install.(*Feature).Check():
'kubernetes' on cluster 'ab' [lib/server/install/feature.go:128]
(duration: 00h00m05.170s)
INFO    [2020-03-31 07:26:58.263][info][31694] Ending addition of
feature 'kubernetes' on cluster 'ab' (elapsed: 00h00m05.170s)
ERROR   [2020-03-31 07:26:58.263][error][31694] --- {task
fb05f3f6-2095-48e8-b43c-725748e15bdf} install.(*Feature).Add():
'kubernetes' on cluster 'ab' [lib/server/install/feature.go:174]:
ERROR OCCURRED: failed to check feature 'kubernetes': rpc error:
code = Internal desc = cannot inspect host: failed to find host
'316e9d97-5823-4ebf-a6f8-9552d786056d'
TRACE   [2020-03-31 07:26:58.263][trace][31694] <<< {task
fb05f3f6-2095-48e8-b43c-725748e15bdf} install.(*Feature).Add():
'kubernetes' on cluster 'ab' [lib/server/install/feature.go:128]
(duration: 00h00m05.170s)
ERROR   [2020-03-31 07:26:58.263][error][31694] [cluster ab] failed
to add feature 'kubernetes': failed to check feature 'kubernetes':
rpc error: code = Internal desc = cannot inspect host: failed to
find host '316e9d97-5823-4ebf-a6f8-9552d786056d'
ERROR   [2020-03-31 07:27:12.163][error][31694] trying to add error
[%!s(<nil>)] to existing error [failed to check feature
'kubernetes': rpc error: code = Internal desc = cannot inspect
host: failed to find host '316e9d97-5823-4ebf-a6f8-9552d786056d']
but failed
ERROR   [2020-03-31 07:27:12.163][error][31694] --- {task
fb05f3f6-2095-48e8-b43c-725748e15bdf}
control.(*Controller).AddNodes(1)
[lib/server/cluster/control/controller.go:174]:  ERROR OCCURRED:
failed to check feature 'kubernetes': rpc error: code = Internal
desc = cannot inspect host: failed to find host
'316e9d97-5823-4ebf-a6f8-9552d786056d'
TRACE   [2020-03-31 07:27:12.164][trace][31694] <<< {task
fb05f3f6-2095-48e8-b43c-725748e15bdf}
control.(*Controller).AddNodes(1)
[lib/server/cluster/control/controller.go:128]
{"error":{"exitcode":6,"message":"failed to check feature
'kubernetes': rpc error: code = Internal desc = cannot inspect
host: failed to find host
'316e9d97-5823-4ebf-a6f8-9552d786056d'"},"result":null,"status":"failure"}

**Comment by vplanche-cssi** [comment]
Looks like metadata of node ab-node-4 are not removed when the first try failed.

**Comment by vplanche-cssi** [comment]
A new branche, hotfix/github#80, has been created with a fix.

The issue not being easily reproductible, depending of provider failure to create new host, it's hard to test it : does a success mean the fix works or does it mean the provider didn't fail to create host (which would trigger the issue) ?

**Comment by oscarpicas** [comment]
Fixed in branch release/v20.03, commit 09a13993b6c6d6a86fd50eb300661a89e6108c97

**Comment by vplanche-cssi** [comment]
Fixed in commit 09a13993b6c6d6a86fd50eb300661a89e6108c97
