### ISSUE TITLE
How does SafeScale compare to other IaC tools

### ISSUE THREAD

**Issue by rsemlal-tas** [CS-SI/SafeScale#82]
Hi,

I am having trouble understanding the scope of SafeScale from the main documentation.

How does it compare to other infrastructure as code solutions like [Terraform](https://www.terraform.io/)? Is it equivalent? Does it provide a completely different set of funtionalities?

In general I think that adding a section that compares this product to similar tools might be beneficial for potential users.

Thanks in advance :)

**Comment by SebastienDorgan** [comment]
Hi,
Thank you for your interest.
There are 2 major differences between Safescale and Terraform:
- SafeScale adopts an imperative/additive strategy and Terraform adopts a descriptive/idempotent strategy.
- SafeScale scripts are portable, the Terraform descriptions must be adapted for each supplier.

SafeScale is better to use when the infrastructure to be controlled is changing and one wishes to deploy identical services on several cloud providers.
Terraform is well suited when you are targeting mainly a particular cloud provider and want to address specific services.
