### ISSUE TITLE
On FlexibleEngine, creating a host with 1 cpu and CentOS 7.7 fails

### ISSUE THREAD

**Issue by vplanche-cssi** [CS-SI/SafeScale#83]
The template selected is s1.small in this case.

At best we get an emergency shell at the first reboot, at worst the boot seems stuck.

Asking for at least 2 cpus works as expected.

Creating the same kind of VM using the GUI of Flexible Engine (without SafeScale customisation) works as expected.

A workaround for now is to ask for at least 2 cpus.

**Comment by oscarpicas** [comment]
Fixed by https://github.com/CS-SI/SafeScale/commit/987e5664f8828811d2123fa4f3ab97575fdf22db
