### ISSUE TITLE
Kubernetes creation not complete due to incorrect URL used to install helm2

### ISSUE THREAD

**Issue by vplanche-cssi** [CS-SI/SafeScale#84]
"Since November 13, 2020, the new location for the stable repository is https://charts.helm.sh/stable and the new location for the incubator repository is https://charts.helm.sh/incubator."

**Comment by remifabas** [comment]
Hello ! I'm trying with this solution : https://stackoverflow.com/questions/65407317/helm-init-failed-is-not-a-valid-chart-repository-or-cannot-be-reached-failed-to

I will keep you informed

**Comment by remifabas** [comment]
in features/k8s.helm2yml
`                            sudo -u {{ .ClusterAdminUsername }} -i helm init \
                                --tiller-tls \
                                --tiller-tls-hostname {{ .Hostname }} \
                                --tiller-tls-cert ${SF_ETCDIR}/helm/pki/tiller.cert.pem \
                                --tiller-tls-key ${SF_ETCDIR}/helm/pki/tiller.key.pem \
                                --tiller-tls-verify \
                                --tls-ca-cert /etc/kubernetes/pki/ca.crt \
                                --service-account tiller \
                                --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
                                || sfFail 247`

to
`              sudo -u {{ .ClusterAdminUsername }} -i helm init \
                  --tiller-tls \
                  --tiller-tls-hostname {{ .Hostname }} \
                  --tiller-tls-cert ${SF_ETCDIR}/helm/pki/tiller.cert.pem \
                  --tiller-tls-key ${SF_ETCDIR}/helm/pki/tiller.key.pem \
                  --stable-repo-url=https://charts.helm.sh/stable  \
                  --tiller-tls-verify \
                  --tls-ca-cert /etc/kubernetes/pki/ca.crt \
                  --service-account tiller \
                  --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
                  || sfFail 247`

**Comment by vplanche-cssi** [comment]
Fix will be included in next v20.06.3 release (coming soon).

In the meantime, it's possible to workaround the issue:
- create a folder `features` in your safescale folder (`$HOME/.safescale` or `/etc/safescale`or folder where `safescaled` is started)
- copy file `features/k8s.helm2.yml` from github repository, tag v20.06, in this folder
- change line suggested by remifabas in comment above (should be line 183)
- restart `safescaled`

SafeScale will then use this custom feature description file to add helm 2 at K8S cluster creation.

**Note**: do not forget to disable the custom feature after upgrade when v20.06.3 is released (renaming k8s.heml2.yml to k8s.helm2.yml.disabled for example); or more definitively remove the custom feature
**Note2**: this works for most (if not all) embedded features in safescaled.

**Comment by vplanche-cssi** [comment]
v20.06.3 will probably never be published. The fix is included in recently published v21.05.0 release candidates.
