### ISSUE TITLE
Problem with the SSH private key

### ISSUE THREAD

**Issue by cbouissoncs** [CS-SI/SafeScale#85]
Following an audit by ADS Cyber Security, a security vulnerability has been identified: the SSH private key of a root account is stored in clear text in user data and is accessible from created VM with a single URL read (confirmed on Flexible Engine).

A modification will therefore be made in Safescale to correct this vulnerability, probably in this way:
- Use of a private key in the user data to manage first connection during VM creation
- Once this first connection has been made, the private key will still be in the user data but it will be deactivated (creation of a new private key but this time not accessible).
Even if the user data private key will be active for a very short time, VM creation is protected by a Security Group.  
 
For VMs already created, a possible workaround is to block access to the Cloud Provider service managing the metadata thanks to a firewall rule (IP: 169.254.169.254).

**Comment by vplanche-cssi** [comment]
The Cloud Provider concerned for now are the ones based on OpenStack, where userdata cannot be cleaned up through API; it should be possible to clear it inside the database used on Openstack Infrastructure to store userdata but this is not exposed to API and need to request this change to the administrative team.

Further investigation will be done ASAP to identify the impact on other Cloud Implementations (AWS, GCP, ...).

**Comment by vplanche-cssi** [comment]
Next major release will contain the mitigation of this issue. For now, it's planned for the end of February 2021.

**Comment by vplanche-cssi** [comment]
Mitigation implemented in commit 4e930c22399c1445e9d7e11d12a716dcd61d1314
Tested and validated successfully: when userdata contains SSH keys (private and public), they are no more related to deployed SSH keys on host

**Comment by vplanche-cssi** [comment]
release candidate v21.05.0-rc1 contains the change.
