### ISSUE TITLE
Cluster subnet CIDR must not overlap with Docker default subnet

### ISSUE THREAD

**Issue by cbouisson-csgroup** [CS-SI/SafeScale#90]
Cluster subnet CIDR should be checked before cluster creation to avoid overlapping with Docker default subnet.

**Comment by vplanche-cssi** [comment]
We will make sure to configure docker to avoid this situation.

Not planned yet though, will update the issue when planned.

**Comment by oscarpicas** [comment]
When subnet CIDR overlaps, a message error is issued: "cidr ... intersects with default docker network"
Merged in fb56304ada65a032ee56cb23f777d731b3a6a7cf
