### ISSUE TITLE
make files working on mac

### ISSUE THREAD

**Issue by gedw99** [CS-SI/SafeScale#95]
The project looks like a nice alternative to terraform enterprise. Really nice design too.

I was wondering is there is any interest in making the makefiles work on Mac ?

The makefile structure is very good. Just a few thing assume linux, and makes it impossible to get going.

**Comment by gedw99** [comment]
``` 

SafeScale git:(master) make

 *************** SAFESCALE BUILD ****************
 If in doubt, try "make all"

BUILD TARGETS:
  all          - Builds all binaries
  help         - Prints this help message
  godocs       - Runs godoc in background at port 6060.
                 Go to (http://localhost:6060/pkg/github.com/CS-SI/)
  install      - Copies all binaries to /Users/apple/workspace/go/bin

TESTING TARGETS:
  metalint     - Runs golangci-lint
  style        - Runs golangci-lint focusing on style issues
  vet          - Runs all checks
  err          - Looks for unhandled errors
  test         - Runs all unit tests
  convey       - Runs goconvey in lib dir
  coverage     - Collects coverage info from unit tests
  show-cov     - Displays coverage info in firefox

DEV TARGETS:
  clean        - Removes files generated by build.
  logclean     - Removes log files generated by build.

➜  SafeScale git:(master) make all
[ERROR] Minimum go version is 1.15 ! 
make: *** [versioncut] Error 1

```

I am on go 1.17 ...

**Comment by vplanche-cssi** [comment]
SafeScale builds perfectly on macOS, but actually, go 1.17 has not been testede/validated to compile SafeScale (no matter what the OS is).

You should downgrade to 1.16 to succeed (I can guarantee it works well with go 1.16.4, it's the release I'm personally used on macOS to build binaries on macOS).

You may find a tool like gobrew handy to manage different go versions.
