### ISSUE TITLE
Fix Doc about Go version 

### ISSUE THREAD

**Issue by gbonnefille** [CS-SI/SafeScale#96]
Doc refers to go 1.14 while `make all` complaints:
```
[ERROR] Minimum go version is 1.15 ! 
make: *** [Makefile:78: versioncut] Error 1
```

* [ ] doc/build/UBUNTU_BUILD.md
* [ ] doc/build/CENTOS_BUILD.md
* [ ] doc/build/DEBIAN_BUILD.md

**Comment by vplanche-cssi** [comment]
What branch did you used ?

**Comment by gbonnefille** [comment]
> What branch did you used ?

Damn! I read doc on `master` and run build on `develop`...
